name: Tymlez CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
    paths-ignore:
      - '**/*.md'

env:
  CI: 'true'
  AWS_SDK_LOAD_CONFIG: 'true'
  AWS_REGION: ap-southeast-2
  AWS_DEFAULT_REGION: ap-southeast-2

jobs:
  install:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'dependabot/')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: restore npm
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package-lock.json') }}

      - name: npm install
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          npm install
          (cd message-broker && tsc --version && ls -al node_modules && ls -al node_modules/@types)

  check:
    runs-on: ubuntu-latest
    needs: install
    if: "!contains(github.ref, 'dependabot/')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: restore npm
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package-lock.json') }}

      - name: npm install
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          npm install
          (cd message-broker && tsc --version && ls -al node_modules && ls -al node_modules/@types)

      - name: Check
        run: |
          (cd message-broker && tsc --version && ls -al node_modules && ls -al node_modules/@types)
          npm run build
          npm run lint

  # deploy-dev:
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   env:
  #     ENV: dev
  #     CLIENT_NAME: '${{ matrix.job }}'
  #     # Paul Debug: needed?
  #     CLOUDSDK_CORE_PROJECT: tymlez-platform-328903

  #   steps:
  #     - name: Get GIT_SHA and GIT_TAG
  #       env:
  #         GIT_TAG: ${{ github.sha }}
  #       run: |
  #         GIT_SHA=${GIT_TAG:0:7}

  #         echo "GIT_SHA=$GIT_SHA"
  #         echo "GIT_SHA=$GIT_SHA" >> $GITHUB_ENV

  #         echo "GIT_TAG=$GIT_TAG"
  #         echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV

  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Use Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '16.x'

  #     - name: npm install
  #       run: |
  #         # Paul Debug
  #         gcloud --version
  #         gcloud container clusters list
  #         npm install

#          Paul Debug
# - name: Deploy
#   run: |
#     npm run deploy
#   env:
#     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#     CLOUDSDK_CORE_PROJECT: tymlez-platform-328903

